
@baseUrl = https://pdhunt.onrender.com/api
@user_id = 645a38389afc0e8369e2ff1d

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZmMjM4ZWNmNzcyN2E2Y2QzMzU5YzciLCJuYW1lIjoiVmluYXkzIiwiZW1haWwiOiJ2aW5heTNAZ21haWwuY29tIiwiaWF0IjoxNjg1NDQ3MDQ0LCJleHAiOjE2ODU1MzM0NDR9.0Nr7qVMFsJ8x4pn24_-o7dRgzAl7H4j3SpX9icOJU6c



@token1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhMzVkYjcwZDFmOTU1MTYyNDVjZTkiLCJuYW1lIjoiQW5tb2wzIiwiZW1haWwiOiJhbm1vbDNAZ21haWwuY29tIiwiaWF0IjoxNjgzNzIyOTE4LCJleHAiOjE2ODM4MDkzMTh9.8sPZj03olHSbmqs6zGp2HbzcKOCKXkbRXI-82eYjhUM

###

POST {{baseUrl}}/user
content-type: application/json
Authorization: Bearer {{token}}

{
    "email":"vinay1@gmail.com"
}

###
POST {{baseUrl}}/auth/signup
content-type: application/json

{
    "name": "Vinay3",
    "email":"vinay3@gmail.com",
    "password": "password@123",
    "role": "admin"
}

###
POST {{baseUrl}}/auth/login
content-type: application/json

{    
    "email":"vinay3@gmail.com",
    "password": "password@123"
}


###
POST {{baseUrl}}/auth/logout
content-type: application/json
Authorization: Bearer {{token1}}



// Tags
###
POST {{baseUrl}}/tag
content-type: application/json
Authorization: Bearer {{token}}

{
    "name":"Artificial Intelligence"
    

}

###
GET {{baseUrl}}/tag
content-type: application/json
Authorization: Bearer {{token}}



###
GET {{baseUrl}}/tag/645a45ad29205a5ac0046864
content-type: application/json
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/product
content-type: application/json
Authorization: Bearer {{token}}

{
    "name":"Upscale",
    "description" : "Upscale is a sales engagement platform that helps sales teams build a consistent pipeline through structured prospecting. Eliminate random prospecting with multi-channel sequences. Identify activities that lead to conversations to book more qualified meetings.",
    "shortDesc" : "Build a consistent pipeline to accelerate revenue generation",
    "icon" : "https://ph-files.imgix.net/d1ab439d-e20a-4dab-9488-20177087c5c0.png",
    "url" : "https://upscale.ai/"
    
}

###

PATCH {{baseUrl}}/product/645b90e767cceb1ea65920f0/vote
content-type: application/json
Authorization: Bearer {{token}}



###

POST {{baseUrl}}/product/645b90e767cceb1ea65920f0/comment
content-type: application/json
Authorization: Bearer {{token1}}

{
    "text":"Not sure what led to a meeting the last time? Im growing Upscale.ai to help sales folks build a consistent pipeline and make revenue a predictable process. Now instead of staying in the dark about what activities are leading to conversations, try this: Structuring your outreach with multi-channel sequences Researching prospects to personalize conversations Automating follow-ups so that you never miss opportunities Tracing activities that lead to meaningful conversations Building and following your best practices for a consistent pipeline Upscale helps with all of this and much more. Take the 21-day free trial to believe it! Lets crush your revenue goals faster with Upscale   Note As a launch offer, were giving you 20% OFF on any paid plan! Also, Im here all day for any questions, feedback, and knowing your thoughts!"
}


###

PATCH {{baseUrl}}/product/645b90e767cceb1ea65920f0/tag
content-type: application/json
Authorization: Bearer {{token1}}


{
    "tag" : "Open Source"
}

###
POST {{baseUrl}}/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fileName"; filename="server.rest"
Content-Type: text/plain

< ./server.rest
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

GET {{baseUrl}}/
content-type: application/json

###

POST {{baseUrl}}/loglevel/debug
content-type: application/json


###

POST {{baseUrl}}/order/checkout
content-type: application/json
Authorization: Bearer {{token}}
